const dict = {
    '0A': "ASTA Linhas Aéreas",
    '0B': "藍色航空",
    '0C': "Cobra Aviation ",
    '0J': "捷俱航空",
    '0K': "科克舍套航空",
    '0V': "越南服務航空",
    '1A': "艾瑪迪斯全球旅遊分銷系統公司",
    '1B': "環亞旅遊資訊系統有限公司",
    '1C': "EDS Information Business",
    '1D': "Radixx Solutions International",
    '1E': "中國民航信息網絡股份有限公司",
    '1F': "INFINI Travel Information",
    '1G': "Travelport dba Worldspan",
    '1H': "Sirena-Travel",
    '1I': "Netjets Aviation",
    '1J': "愛克森斯國際科技有限公司",
    '1K': "Sutra",
    '1L': "CitizenPlane",
    '1M': "JSC Transport Automated Information Systems ",
    '1N': "Navitaire",
    '1P': "Travelport dba Worldspan ",
    '1Q': "InteliSys Aviation Systems",
    '1R': "JR Technologies Ireland",
    '1S': "Sabre",
    '1T': "Hitit Bilgisayar Hizmetleri A.S.",
    '1U': "ITA Software Inc.",
    '1V': "阿波羅電腦訂票系統",
    '1W': "CTW Consulting",
    '1X': "Fly Branson Travel",
    '1Y': "DXC Technology Services LLC",
    '1Z': "Bird Information Systems Private Limited",
    '2A': "德國鐵路",
    '2B': "Albawings",
    '2C': "法國鐵路",
    '2D': "Eastern Airlines, LLC",
    '2E': "Smokey Bay Air",
    '2F': "Two Taxi Aereo Ltda",
    '2G': "Angara Airlines",
    '2H': "大力士高速列車",
    '2I': "秘魯星航空",
    '21 Air': " 美國",
    '2J': "布基納航空",
    '2K': "厄瓜多哥倫比亞航空",
    '2L': "赫爾維蒂航空",
    '2M': "Maya Island Air",
    '2N': "Yuzmashavia",
    '2O': "Redemption Inc.",
    '2P': "菲律賓飛鷹航空",
    '2Q': "Air Cargo Carriers",
    '2R': "Atlantis European Airways",
    '2S': "AIR STORK SRL",
    '2T': "Turbo Megha Airways",
    '2U': "Sun d'Or International Airlines",
    '2V': "美國國鐵",
    '2W': "Welcome Air",
    '2Y': "My Indo Airlines",
    '2Z': "Passaredo Transportes Aereos S.A.",
    '3A': "珠江客運",
    '3B': "Transportes Interilhas de Cabo Verde",
    '3C': "Air Chathams",
    '3D': "Dokasch GmBH",
    '3E': "Air Choice One",
    '3G': "Asia Cargo Express",
    '3H': "因紐特航空",
    '3J': "吉普航空",
    '3K': "捷星亞洲航空",
    '3L': "InterSky",
    '3M': "銀色航空",
    '3N': "烏格航空",
    '3O': "摩洛哥阿拉伯航空",
    '3Q': "雲南航空",
    '3R': "Divi Divi Air",
    '3S': "邏輯航空",
    '3T': "Tarco Airlines",
    '3U': "四川航空",
    '3V': "ASL比利時航空",
    '3W': "馬拉威航空",
    '3X': "Premier Trans Aire",
    '3Y': "Baseops International",
    '3Z': "Smartwings Poland",
    '4A': "Aero Transporte S.A.",
    '4B': "Boutique Air",
    '4C': "哥倫比亞南美航空",
    '4D': "西奈航空",
    '4E': "Stabo Air",
    '4F': "Freedom Airline Express",
    '4G': "俄羅斯天然氣工業航空",
    '4H': "孟加拉聯合航空",
    '4J': "United Caribbean Airlines",
    '4K': "Kenn Borek Air",
    '4L': "Líneas Aéreas Suramericanas",
    '4M': "阿根廷南美航空",
    '4N': "Air North",
    '4O': "英特捷特航空",
    '4P': "Regional Sky Charter",
    '4R': "Star East Airline",
    '4S': "Solar Cargo",
    '4T': "Transwest Air",
    '4U': "德國之翼航空",
    '4V': "江原航空",
    '4W': "同盟航空",
    '4X': "水星航空",
    '4Y': "空中巴士",
    '4Z': "南非連接航空",
    '5A': "Alpine Air Express",
    '5B': "百善航空",
    '5C': "CAL Cargo Air Lines",
    '5D': "墨西哥國際連接航空",
    '5F': "飛一航空",
    '5G': "Skyservice",
    '5H': "Fly540",
    '5I': "Alsa Grupo SLU",
    '5J': "宿霧太平洋航空",
    '5K': "HiFly",
    '5L': "Transportes Aereos Costarricenses",
    '5M': "FlyMontserrat",
    '5N': "智慧航空",
    '5O': "法國ASL航空 ",
    '5P': "Skyeurope Airlines Hungary",
    '5Q': "Holiday Europe",
    '5R': "RUTACA Airlines",
    '5S': "Global Air Transport",
    '5T': "北加拿大航空",
    '5U': "Transportes Aéreos Guatemaltecos",
    '5V': "Everts Air Cargo",
    '5W': "Astraeus Airlines",
    '5X': "優比速航空",
    '5Y': "亞特拉斯航空",
    '5Z': "CemAir",
    '6A': "Armenia Airways",
    '6B': "北歐途易航空",
    '6C': "CONNECT LINHAS AEREAS SA",
    '6D': "Smartwings Slovakia",
    '6E': "印地高航空",
    '6G': "奔向天空航空",
    '6H': "以斯雷航空",
    '6I': "Air Alsie",
    '6J': "亞洲天網航空",
    '6L': "Aklak Air",
    '6M': "Maximus Air Cargo",
    '6N': "Niger Airlines",
    '6O': "Orbest",
    '6P': "Club Air",
    '6Q': "Cham Wings Airlines",
    '6R': "聯盟貨運航空",
    '6S': "沙烏地海灣航空",
    '6U': "Air Ukraine",
    '6V': "Avanza Group",
    '6W': "波士尼亞航空",
    '6Y': "山貓航空",
    '6Z': "烏克蘭貨運航空",
    '7A': "Express Air Cargo",
    '7C': "濟州航空",
    '7C': "科尼航空",
    '7D': "Madagasikara Airways",
    '7E': "Sylt Air",
    '7F': "第一航空",
    '7G': "星悅航空",
    '7H': "阿拉斯加烏鴉航空 ",
    '7I': "Air Libya",
    '7J': "塔吉克航空",
    '7K': "CSafe Global",
    '7L': "Silk Way West Airlines",
    '7M': "MAP Linhas Aéreas",
    '7N': "MetroJets, LLC",
    '7O': "Smartwings Hungary",
    '7P': "Air Panama",
    '7Q': "Elite Airways",
    '7R': "俄線航空",
    '7S': "Ryan Air Services",
    '7T': "Aero Express del Ecuador - Trans A",
    '7U': "Alpha Air Transport dba Commercial Aviation Services",
    '7V': "聯邦航空",
    '7W': "風玫瑰航空",
    '7Y': "Mann Yadanarpon Airlines",
    '7Z': "EZAir",
    '8A': "亞特拉斯藍天航空",
    '8B': "翎亞航空",
    '8C': "金光飛航",
    '8D': "FitsAir",
    '8E': "白令航空",
    '8F': "聖多美普林西比航空",
    '8G': "Instone Air Services Ltd",
    '8H': "BH航空",
    '8I': "MyAir",
    '8J': "EcoJet",
    '8K': "凱邁爾航空",
    '8L': "雲南祥鵬航空",
    '8M': "緬甸國際航空",
    '8N': "Regional Air",
    '8O': "西海岸航空",
    '8P': "太平洋海岸航空",
    '8Q': "Onur Air",
    '8R': "Transporte Aereo Regional do Interior Paulista/Edelweiss Air",
    '8T': "Air Tindi",
    '8U': "泛非航空",
    '8V': "Wright Air Service",
    '8W': "Fly All Ways",
    '8Y': "Pan Pacific Airlines",
    '8Z': "剛果航空 ",
    '9A': "Gran Colombia de Aviación",
    '9B': "AccesRail and Partner Railways",
    '9C': "春秋航空",
    '9D': "天驕航空",
    '9E': "Endeavor Air",
    '9F': "歐洲之星",
    '9G': "9G Rail",
    '9H': "長安航空",
    '9I': "印度地區航空",
    '9J': "丹納航空",
    '9K': "Cape Air",
    '9L': "AirTanker Services",
    '9M': "Central Mountain Air",
    '9N': "Tropic Air",
    '9O': "The Cargo Flights",
    '9R': "SATENA",
    '9S': "Southern Air",
    '9T': "Air ACT",
    '9U': "摩爾多瓦航空",
    '9V': "Avior Airlines",
    '9W': "捷特航空",
    '9X': "Southern Airway Express",
    '9Y': "National Airways Ethiopia",
    'A1': "A.P.G. Distribution System",
    'A2': "Cielos Airlines",
    'A3': "愛琴海航空",
    'A4': "Azimuth Airlines",
    'A5': "霍浦航空",
    'A6': "紅土航空",
    'A7': "Calafia Airlines",
    'A8': "Aerolink Uganda",
    'A9': "喬治亞航空",
    'AA': "美國航空",
    'AB': "柏林航空",
    'AC': "加拿大航空",
    'AD': "藍色巴西航空",
    'AE': "華信航空",
    'AF': "法國航空",
    'AG': "ASL Airlines Ireland",
    'AH': "阿爾及利亞航空",
    'AI': "印度航空",
    'AJ': "Aztec Worldwide Airlines",
    'AK': "亞洲航空",
    'AL': "Transaviaexport Cargo Airlines",
    'AM': "墨西哥國際航空",
    'AN': "Advanced Air",
    'AO': "Air Juan",
    'AP': "阿爾巴之星航空",
    'AQ': "九元航空",
    'AR': "阿根廷航空",
    'AS': "阿拉斯加航空",
    'AT': "摩洛哥皇家航空",
    'AU': "阿根廷南方航空",
    'AV': "哥倫比亞航空",
    'AW': "非洲世界航空",
    'AX': "州際航空",
    'AY': "芬蘭航空",
    'AZ': "義大利航空",
    'B0': "公務航空",
    'B1': "布加勒斯特航空",
    'B2': "白俄羅斯航空",
    'B3': "不丹航空",
    'B4': "ZanAir",
    'B5': "東非旅行航空",
    'B6': "捷藍航空",
    'B7': "立榮航空",
    'B8': "厄利垂亞航空",
    'B9': "伊朗陸游航空公司",
    'BA': "英國航空",
    'BB': "海運航空",
    'BC': "天馬航空",
    'BD': "英倫航空",
    'BE': "歐洲澤西島航空",
    'BF': "法國蜜蜂航空",
    'BG': "孟加拉航空",
    'BH': "Bismillah Airlines",
    'BI': "汶萊皇家航空",
    'BJ': "突尼西亞尼韋爾航空",
    'BK': "奧凱航空",
    'BL': "太平洋航空",
    'BM': "Air Sicilia",
    'BN': "Braniff International Airways",
    'BO': "藍鳥貨運航空公司",
    'BP': "波札那航空",
    'BQ': "Bukovyna Airlines",
    'BR': "長榮航空",
    'BS': "孟加拉優速航空",
    'BT': "波羅的海航空",
    'BU': "Compagnie Africaine d'Aviation",
    'BV': "藍景航空 ",
    'BW': "加勒比人航空 ",
    'BX': "釜山航空",
    'BY': "英國途易航空",
    'BZ': "Blue Bird Airways",
    'C0': "One Caribbean Ltd",
    'C1': "Tectimes Sudamericana",
    'C2': "木棉洲際航空",
    'C3': "翠特航空",
    'C4': "Conquest Air",
    'C5': "CommutAir",
    'C6': "Unilode Aviation Solutions New Zealand Limited",
    'C7': "Cinnamon Air",
    'C8': "Cargolux Italia",
    'C9': "Alphaland Aviation",
    'CA': "中國國際航空公司",
    'CB': "Trans Caribbean Air Export Import",
    'CC': "亞特蘭大冰島航空",
    'CD': "Corendon Dutch Airlines",
    'CE': "Chalair Aviation",
    'CF': "中國郵政航空",
    'CG': "巴布亞紐幾內亞航空",
    'CH': "伯米吉航空",
    'CI': "中華航空",
    'CJ': "英航城市飛行者",
    'CK': "中國貨運航空公司",
    'CL': "漢莎城際航空",
    'CM': "巴拿馬航空",
    'CN': "大新華航空",
    'CO': "美國大陸航空",
    'CP': "指南針航空 ",
    'CQ': "Coastal Aviation",
    'CR': "UBM Aviation - OAG",
    'CS': "UComlux Aruba",
    'CS[2]': "密克羅尼西亞大陸航空",
    'CT': "義大利城市快線航空",
    'CU': "古巴航空",
    'CV': "盧森堡國際貨運航空",
    'CW': "馬紹爾群島航空",
    'CX': "國泰航空",
    'CY': "查理航空",
    'CZ': "中國南方航空公司",
    'D0': "敦豪貨運 ",
    'D1': "AIR4 Passenger Service Systems",
    'D2': "北方鋼鐵航空",
    'D3': "達洛航空",
    'D4': "GEO SKY",
    'D5': "DHL Aero Expreso",
    'D6': "南非國際航空",
    'D7': "全亞洲航空",
    'D8': "挪威國際航空",
    'D9': "Donavia",
    'DA': "喬治亞航空",
    'DB': "MALETH-AERO",
    'DC': "布拉森支線航空",
    'DD': "皇雀航空",
    'DE': "神鷹航空",
    'DF': "禿鷹航空",
    'DG': "宿翱航空",
    'DH': "Norwegian Air Norway",
    'DI': "Norwegian Air UK",
    'DJ': "日本亞洲航空",
    'DK': "Sunclass Airlines",
    'DL': "達美航空",
    'DM': "馬士基航空",
    'DN': "Air Deccan",
    'DO': "Sky High Aviation Services",
    'DP': "勝利航空",
    'DQ': "海岸航空運輸公司",
    'DR': "瑞麗航空",
    'DS': "瑞士易捷航空",
    'DT': "安哥拉航空",
    'DU': "Sky Jet M.G. Inc.",
    'DV': "斯卡特航空 ",
    'DW': "大丹航空",
    'DX': "丹麥航空運輸公司",
    'DY': "挪威航空快線",
    'DZ': "東海航空",
    'E2': "歐羅巴歐洲之翼航空",
    'E3': "新時代航空",
    'E4': "Enter Air Spolka z.o.o.",
    'E5': "埃及阿拉伯航空",
    'E6': "Bringer Air Cargo Taxi Aereo Ltda",
    'E7': "Estafeta Carga Aérea",
    'E8': "Alpi Eagles",
    'E9': "埃福洛普航空",
    'EA': "東方航空",
    'EB': "Wamos Air",
    'EC': "歐洲易捷航空",
    'ED': "探索航空",
    'EE': "諾迪卡航空",
    'EF': "AerCaribe",
    'EG': "Enerjet",
    'EH': "全日空之翼",
    'EI': "愛爾蘭航空",
    'EJ': "新英格蘭航空",
    'EK': "阿聯航空",
    'EL': "葉林航空",
    'EM': "帝國航空",
    'EN': "多羅米提航空",
    'EO': "皮格斯航空",
    'EP': "伊朗阿塞曼航空",
    'EQ': "厄瓜多航空",
    'ER': "SereneAir",
    'ES': "Estelar Latinoamerica",
    'ET': "衣索比亞航空",
    'EU': "成都航空",
    'EV': "快捷航空",
    'EW': "歐洲之翼",
    'EX': "Avianca Express",
    'EY': "阿提哈德航空",
    'EZ': "斯堪地那維亞陽光航空",
    'F0': "Fly Jor dan",
    'F1': "Farelogix",
    'F2': "Safarilink Aviation",
    'F3': "flyadeal",
    'F4': "弗拉門戈航空",
    'F5': "空環貨運航空",
    'F6': "中國航空",
    'F7': "艾菲航空",
    'F8': "天才航空",
    'F9': "邊疆航空",
    'FA': "薩法航空",
    'FB': "保加利亞航空",
    'FC': "Fly Corporate",
    'FD': "泰國亞洲航空",
    'FE': "遠東航空",
    'FF': "Airshop B.V.",
    'FG': "阿里亞納阿富汗航空",
    'FH': "自由鳥航空",
    'FI': "冰島航空",
    'FJ': "斐濟航空",
    'FK': "KF 貨運",
    'FL': "Air Leap",
    'FM': "上海航空",
    'FN': "Fastjet Zimbabwe",
    'FO': "Flybondi",
    'FP': "FlyPelican",
    'FQ': "Flyest Lineas Aereas",
    'FR': "瑞安航空",
    'FS': "西法克斯航空",
    'FT': "FlyEgypt",
    'FU': "福州航空",
    'FV': "俄羅斯國家航空",
    'FW': "伊別克斯航空",
    'FX': "聯邦快遞航空",
    'FY': "飛螢航空",
    'FZ': "杜拜航空",
    'G0': "Alianza Glancelot",
    'G3': "高爾航空 ",
    'G4': "忠實航空",
    'G5': "華夏航空",
    'G6': "吳哥航空",
    'G7': "GoJet Airlines",
    'G8': "捷行航空",
    'G9': "阿拉伯航空",
    'GA': "嘉魯達印尼航空",
    'GB': "ABX 航空",
    'GC': "Global Feeder Services",
    'GD': "Aviair PTY",
    'GE': "Global Aviation",
    'GF': "海灣航空",
    'GG': "Sky Lease Cargo",
    'GH': "Globus Airlines",
    'GI': "中原龍浩航空",
    'GJ': "長龍航空",
    'GK': "捷星日本航空",
    'GL': "格陵蘭航空",
    'GM': "日耳曼飛航",
    'GN': "加彭航空",
    'GO': "ULS貨運航空",
    'GP': "APG Airlines",
    'GQ': "天空快運",
    'GR': "奧爾德尼航空服務",
    'GS': "天津航空",
    'GT': "桂林航空",
    'GB航空': "",
    'GU': "瓜地馬拉航空",
    'GV': "Grant Aviation",
    'GW': "GetJet Airlines",
    'GX': "北部灣航空",
    'GY': "多彩貴州航空",
    'GZ': "拉羅東加航空",
    'H1': "Hahn Air Systems",
    'H2': "智利天空航空",
    'H3': "Thomas Cook Aviation",
    'H5': "Thomas Cook Airlines Balearics",
    'H6': "保加利亞包機",
    'H8': "秘魯天空航空",
    'H9': "喜瑪拉雅航空",
    'HA': "夏威夷航空",
    'HB': "亞洲亞特蘭提克航空",
    'HC': "塞內加爾航空",
    'HD': "北海道國際航空",
    'HE': "瓦爾特航空",
    'HF': "象牙海岸航空",
    'HG': "Hibernian Airlines",
    'HH': "塔班航空",
    'HI': "Papillon Airways",
    'HJ': "塔斯曼貨運航空",
    'HK': "Skippers Aviation",
    'HM': "塞席爾航空",
    'HO': "吉祥航空",
    'HP': "Amapola Flyg",
    'HQ': "比利時托馬斯庫克航空",
    'HR': "漢亞航空",
    'HS': "Heli Securite Helicopter Airline",
    'HT': "Air Horizont",
    'HU': "海南航空",
    'HV': "泛航航空",
    'HW': "North-Wright Airways",
    'HX': "香港航空",
    'HY': "烏茲別克航空",
    'HZ': "阿芙樂爾航空",
    'I2': "西班牙航空快運",
    'I3': "科航服務有限公司",
    'I4': "Island Air Express",
    'I5': "印度亞洲航空",
    'I6': "哈拉帕航空",
    'I8': "Izhavia",
    'I9': "中州航空",
    'IA': "伊拉克航空",
    'IB': "西班牙國家航空",
    'ID': "巴澤航空",
    'IE': "所羅門航空",
    'IF': "巴格達航空",
    'IG': "義大利航空",
    'IH': "Southern Sky Airlines",
    'II': "IBC航空",
    'IJ': "春秋航空日本",
    'IK': "吉里巴斯航空",
    'IL': "特里迦納航空",
    'IM': "Jupiter Jet",
    'IN': "NAM Air",
    'IO': "伊爾航空",
    'IP': "One Airlines",
    'IQ': "哈薩克航空",
    'IR': "伊朗航空",
    'IS': "Sepehran Airlines",
    'IT': "台灣虎航",
    'IU': "SW Italia",
    'IV': "福建航空",
    'IW': "飛翼航空",
    'IX': "印度快運航空",
    'IY': "葉門航空",
    'IZ': "阿基亞以色列航空",
    'J1': "一捷航空",
    'J2': "亞塞拜然航空",
    'J3': "西北航空 ",
    'J4': "巴德爾航空",
    'J5': "Alaska Seaplane Service",
    'J6': "Jet Ops",
    'J7': "Afrijet Business Service",
    'J8': "成功航空",
    'J9': "半島航空",
    'JA': "捷聰航空",
    'JB': "Helijet",
    'JC': "日本空中通勤",
    'JD': "首都航空",
    'JE': "芒果航空",
    'JF': "捷特亞洲航空",
    'JG': "Airline Container Leasing",
    'JH': "富士夢幻航空",
    'JI': "梅拉傑航空",
    'JJ': "巴西天馬航空",
    'JK': "AerCaribe",
    'JL': "日本航空",
    'JM': "牙買加航空",
    'JN': "Livingston Compagnia Aerea",
    'JO': "Jasmin Airways",
    'JP': "亞德里亞航空",
    'JQ': "捷星航空",
    'JR': "幸福航空",
    'JS': "高麗航空",
    'JT': "獅子航空",
    'JU': "塞爾維亞航空",
    'JV': "貝爾斯金航空",
    'JW': "香草航空",
    'JX': "星宇航空",
    'JY': "國米加勒比海航空",
    'K2': "PAKLOOK AIR",
    'K3': "塔泉航空",
    'K4': "卡利塔航空",
    'K5': "港口航空",
    'K6': "柬埔寨吳哥航空",
    'K7': "嘎莫薩航空",
    'K8': "InterJet West",
    'K9': "卡利塔包機",
    'KA': "國泰港龍航空",
    'KB': "不丹皇家航空",
    'KC': "阿斯塔納航空",
    'KD': "Western Global Airlines",
    'KE': "大韓航空",
    'KF': "比利時航空",
    'KG': "青檸航空",
    'KH': "阿羅哈貨運航空",
    'KI': "克拉斯諾亞爾斯克航空",
    'KJ': "仁川航空",
    'KK': "阿特拉斯全球航空",
    'KL': "荷蘭皇家航空",
    'KM': "馬爾他航空",
    'KN': "中國聯合航空",
    'KO': "阿拉斯加中央快運",
    'KP': "ASKY Airlines",
    'KQ': "肯亞航空",
    'KR': "柬埔寨航空",
    'KS': "半島航空",
    'KT': "Mahogany Air",
    'KU': "科威特航空",
    'KV': "Sky Regional Airlines",
    'KX': "開曼航空",
    'KY': "昆明航空",
    'KZ': "日本貨物航空",
    'L2': "林登貨運航空",
    'L3': "DHL",
    'L4': "義大利勞達航空",
    'L5': "大西洋輔助航空",
    'L6': "茅利塔尼亞國際航空",
    'L7': "哥倫比亞南美貨運航空",
    'L8': "阿弗里奇航空",
    'L9': "Bristow U.S.",
    'LA': "智利南美航空",
    'LB': "Bul Air",
    'LC': "Grupo Corporativo Skyway",
    'LD': "香港華民航空",
    'LE': "瑞典挪威航空",
    'LF': "Contour Airlines",
    'LG': "盧森堡航空",
    'LH': "漢莎航空",
    'LI': "背風群島航空",
    'LJ': "真航空",
    'LK': "Lao Skyway",
    'LL': "邁阿密國際航空",
    'LM': "洛根航空",
    'LN': "利比亞航空",
    'LO': "波蘭航空",
    'LP': "秘魯南美航空",
    'LQ': "瀾湄航空 ",
    'LR': "Avianca Costa Rica",
    'LS': "捷特二航空",
    'LT': "龍江航空",
    'LU': "南美快運航空",
    'LV': "水平航空",
    'LW': "太平洋之翼",
    'LX': "瑞士國際航空",
    'LY': "以色列航空",
    'LZ': "連接航空",
    'M0': "蒙古航空",
    'M1': "MHS Aviation ",
    'M3': "巴西南美貨運航空",
    'M4': "郵政貨運航空",
    'M5': "肯莫爾航空",
    'M6': "美捷國際航空",
    'M7': "馬斯航空",
    'M8': "天捷航空",
    'M9': "馬達西奇公司",
    'MA': "匈牙利航空",
    'MB': "MNG 航空",
    'MC': "美國空軍機動司令部",
    'MD': "馬達加斯加航空",
    'ME': "中東航空",
    'MF': "廈門航空",
    'MG': "伊斯尼斯航空",
    'MG': "Midex 航空",
    'MH': "馬來西亞航空",
    'MI': "勝安航空",
    'MJ': "MyWay Airlines",
    'MK': "模里西斯航空",
    'ML': "地中海航空",
    'MM': "樂桃航空",
    'MN': "南非商務航空",
    'MO': "泰然航空",
    'MP': "馬丁航空",
    'MQ': "特使航空",
    'MR': "匈奴航空",
    'MS': "埃及航空",
    'MT': "托馬斯庫克航空",
    'MU': "中國東方航空",
    'MV': "地中海航空",
    'MW': "莫庫勒勒航空",
    'MX': "墨西哥航空",
    'MY': "馬來西亞之翼航空",
    'MZ': "天草航空",
    'N1': "Darwin Travel Technology",
    'N3': "Vuela El Salvador S.A. de C.V.",
    'N4': "北風航空",
    'N5': "Nolinor Aviation",
    'N7': "My Jet Xpress Airlines",
    'N8': "美國國家航空",
    'N9': "Novair",
    'NA': "尼斯馬航空",
    'NB': "史特靈銀航空",
    'NC': "北方貨運航空",
    'ND': "天翼航空",
    'NE': "尼斯馬航空",
    'NF': "萬那杜航空",
    'NG': "Aero Contractors ",
    'NH': "全日本空輸",
    'NI': "葡萄牙航空運輸",
    'NJ': "Niger Airways",
    'NK': "精神航空",
    'NL': "Amelia International",
    'NN': "香港中旅汽車服務",
    'NO': "勒奧斯航空 ",
    'NP': "尼羅河航空",
    'NQ': "全日空日本航空",
    'NR': "Manta Air",
    'NS': "河北航空",
    'NT': "加那利航空",
    'NU': "日本越洋航空",
    'NV': "中部航空",
    'NW': "西北航空",
    'NX': "澳門航空",
    'NY': "冰島國內航空",
    'NZ': "紐西蘭航空",
    'O2': "AIRDIALOG",
    'O3': "順豐航空",
    'O4': "ORANGE2FLY AIRLINES",
    'O6': "巴西哥倫比亞航空",
    'O8': "泰國暹邏航空",
    'O9': "Nova Airways",
    'OA': "奧林匹克航空",
    'OB': "玻利維亞航空",
    'OC': "東方空橋",
    'OD': "馬印航空",
    'OE': "Lauda ",
    'OF': "跨越航空",
    'OG': "Star Air ",
    'OH': "PSA 航空",
    'OI': "Hinterland Aviation",
    'OJ': "牙買加飛天航空",
    'OK': "捷克航空",
    'OL': "玻里尼西亞航空",
    'OM': "蒙古民用航空",
    'ON': "奧爾航空",
    'OO': "天西航空",
    'OP': "Passion Air",
    'OQ': "重慶航空",
    'OR': "荷蘭途易旅遊",
    'OS': "奧地利航空",
    'OT': "Tchadia Airlines",
    'OU': "克羅埃西亞航空",
    'OV': "SalamAir",
    'OW': "Skyward Express",
    'OX': "泰國東方航空",
    'OY': "奧斯特拉爾航空",
    'OZ': "韓亞航空",
    'P0': "Proflight Zambia",
    'P1': "Aviation Technologies Inc.",
    'P2': "Airkenya Express",
    'P4': "和平航空",
    'P5': "Wingo ",
    'P6': "帕斯卡航空 ",
    'P7': "Russian Sky Airlines",
    'P8': "SprintAir",
    'P9': "亞太航空 ",
    'PA': "藍色航空",
    'PB': "省際航空",
    'PC': "飛馬航空",
    'PD': "波特航空",
    'PE': "People's",
    'PF': "AirSial",
    'PG': "曼谷航空",
    'PH': "Pionair Australial",
    'PI': "保羅航空",
    'PJ': "聖皮耶航空",
    'PK': "巴基斯坦國際航空",
    'PL': "南部包機航空",
    'PM': "加那利亞航空",
    'PN': "西部航空",
    'PO': "博立貨運航空",
    'PP': "Jet Aviation",
    'PQ': "SkyUp",
    'PR': "菲律賓航空",
    'PS': "烏克蘭國際航空",
    'PT': "Piedmont Airlines",
    'PU': "Plus Ultra Líneas Aéreas",
    'PV': "St Barth Commuter",
    'PW': "坦尚尼亞精密航空 ",
    'PX': "新幾內亞航空",
    'PY': "蘇利南航空",
    'PZ': "巴拉圭天馬航空",
    'Q1': "PT. Sqiva Sistem",
    'Q2': "馬爾地夫國家航空",
    'Q3': "Anguilla Air Services",
    'PB航空': "",
    'Q4': "Euroairlines, S.L.",
    'Q5': "40英里航空",
    'Q6': "哥斯大黎加沃拉里斯航空",
    'Q7': "巴哈馬天際航空",
    'Q8': "剛果運輸航空",
    'Q9': "Green Africa Airways",
    'QA': "希姆伯爾航空",
    'QB': "格什姆島航空",
    'QC': "喀麥隆航空",
    'QD': "柬埔寨景成國際航空",
    'QE': "Express Freighters Australia",
    'QF': "澳洲航空",
    'QG': "連城航空",
    'QH': "越竹航空 ",
    'QI': "Ibom Air",
    'QJ': "Jet Airways",
    'QK': "加拿大爵士航空",
    'QL': "雷射航空",
    'QM': "Monacair",
    'QN': "Skytrans Airlines",
    'QQ': "澳洲聯盟航空",
    'QR': "卡達航空",
    'QS': "Smart Wings",
    'QT': "哥倫比亞航空貨運",
    'QU': "Azur Air Ukraine",
    'QV': "寮國航空",
    'QW': "青島航空",
    'QX': "地平綫航空",
    'QY': "歐洲航空運輸公司",
    'QZ': "印尼亞洲航空",
    'R0': "Tantalus Air",
    'R1': "Zapways",
    'R2': "Groupe Transair",
    'R3': "雅庫茨克航空",
    'R4': "Real Tonga",
    'R5': "約旦航空",
    'R6': "DAT LT",
    'R7': "Unilode Aviation Solutions Switzerland",
    'R9': "Trans Executive Airlines",
    'RA': "尼泊爾航空",
    'RB': "敘利亞阿拉伯航空",
    'RC': "大西洋航空公司",
    'RE': "斯托巴特航空",
    'RF': "Aero K Airlines",
    'RG': "羅塔納噴射航空",
    'RH': "香港貨運航空",
    'RI': "曼達拉欣豐虎航",
    'RJ': "皇家約旦航空",
    'RK': "英國瑞安航空",
    'RL': "俄羅斯皇家航空",
    'RM': "Aircompany Armenia",
    'RN': "清真航空",
    'RO': "羅馬尼亞航空",
    'RP': "Budapest Aircraft Service",
    'RQ': "卡姆航空",
    'RR': "瑞安陽光航空",
    'RS': "首爾航空",
    'RT': "韃靼斯坦東南航空",
    'RU': "空橋貨運航空",
    'RV': "加拿大胭脂航空",
    'RW': "菲律賓皇家航空",
    'RX': "麗晶航空",
    'RY': "江西航空",
    'RZ': "薩莎航空",
    'S0': "Aerolíneas Sosa",
    'S1': "漢莎系統",
    'S2': "捷特萊特航空",
    'S3': "SATCO, INC.",
    'S4': "亞速爾國際航空",
    'S5': "小星球航空",
    'S6': "日出航空",
    'S7': "西伯利亞航空",
    'S8': "天空首都航空",
    'SA': "南非航空",
    'SB': "喀里多尼亞航空",
    'SC': "山東航空",
    'SD': "蘇丹航空",
    'SE': "法國特大航空",
    'SF': "塔斯利航空",
    'SG': "香料航空",
    'SH': "Sharp Airlines",
    'SI': "藍色群島航空",
    'SJ': "三佛齊航空",
    'SK': "北歐航空",
    'SL': "泰國獅子航空",
    'SM': "開羅航空",
    'SN': "布魯塞爾航空",
    'SO': "Syphax Airlines",
    'SP': "亞速爾航空",
    'SQ': "新加坡航空",
    'SR': "Sundair",
    'SS': "科西嘉國際航空",
    'ST': "Air Thanlwin",
    'SU': "俄羅斯航空",
    'SV': "沙烏地阿拉伯航空",
    'SW': "納米比亞航空",
    'SX': "Skywagon Corporation",
    'SY': "太陽城航空",
    'SZ': "索蒙航空",
    'T0': "秘魯哥倫比亞航空",
    'T1': "Avtrasoft Limited",
    'T3': "英國東方航空",
    'T4': "Rhoades Aviation",
    'T5': "土庫曼航空",
    'T6': "AirSWIFT",
    'T7': "Twin Jet",
    'T9': "環子午線航空",
    'TA': "哥倫比亞薩爾瓦多航空",
    'TB': "捷特飛航空",
    'TC': "坦尚尼亞航空",
    'TD': "歐洲亞特蘭提斯航空",
    'TE': "立陶宛航空",
    'TF': "布拉森支線航空服務",
    'TG': "泰國國際航空",
    'TH': "拉亞航空",
    'TJ': "貿易風航空 ",
    'TK': "土耳其航空",
    'TL': "澳洲北方航空",
    'TM': "LAM莫三比克航空",
    'TN': "大溪地航空",
    'TO': "法國泛航航空",
    'TP': "葡萄牙航空",
    'TQ': "串聯航空",
    'TR': "酷航",
    'TS': "加拿大越洋航空",
    'TT': "澳洲虎航",
    'TU': "突尼西亞航空",
    'TV': "西藏航空",
    'TW': "德威航空",
    'TX': "加勒比海航空",
    'TY': "喀里多尼亞空中運輸",
    'U1': "Videcom International",
    'U2': "易捷航空",
    'U3': "天門航空",
    'U4': "佛陀航空",
    'U5': "卡妮娜航空",
    'U6': "烏拉爾航空",
    'U7': "Uniworld Air Cargo",
    'U8': "圖斯航空",
    'U9': "Unilode Aviation Solutions",
    'UA': "聯合航空",
    'UB': "緬甸航空",
    'UC': "智利南美貨運航空",
    'UD': "UR AIRLINES",
    'UE': "Ultimate Air Shuttle",
    'UF': "石油航空服務公司",
    'UG': "突尼西亞航空快運",
    'UH': "AtlasGlobal Ukraine",
    'UI': "合金航空 ",
    'UJ': "馬斯利亞通用航空",
    'UK': "維斯塔拉航空",
    'UL': "斯里蘭卡航空",
    'UM': "辛巴威航空",
    'UN': "亞聯公務機",
    'UO': "香港快運航空",
    'UP': "巴哈馬航空",
    'UQ': "烏魯木齊航空",
    'UR': "烏干達航空 ",
    'US': "全美航空",
    'UT': "烏塔航空",
    'UU': "南方航空",
    'UV': "Universal Airways",
    'UW': "友和道通航空",
    'UX': "歐羅巴航空",
    'UY': "Sky Prime Aviation",
    'UZ': "Buraq Air",
    'V0': "委內瑞拉航空",
    'V1': "IBS Software Services Americas",
    'V2': "Avialeasing",
    'V3': "卡帕特航空",
    'V4': "別克斯航空連結",
    'V5': "Aerovías DAP",
    'V6': "VI Airlink",
    'V7': "維羅提航空",
    'V8': "阿特朗航空",
    'V9': "歐洲凡斯航空",
    'VA': "維珍澳洲航空",
    'VB': "愉快空中巴士航空",
    'VE': "易飛航空",
    'VG': "Vipper BV",
    'VH': "哥倫比亞愉快航空",
    'VI': "伏爾加-聶伯航空",
    'VJ': "越捷航空",
    'VK': "Level Europe",
    'VL': "VIA航空",
    'VM': "曼斯航空",
    'VN': "越南航空",
    'VO': "Voyage Air",
    'VP': "Flyme ",
    'VQ': "更始航空",
    'VR': "維德角航空",
    'VS': "維珍大西洋航空",
    'VT': "大溪地航空",
    'VV': "秘魯愉快航空",
    'VW': "Aeromar",
    'VX': "維珍美國航空",
    'VY': "伏林航空",
    'VZ': "泰國越捷航空",
    'W1': "World Ticket Ltd",
    'W2': "Flexflight",
    'W3': "阿瑞克航空",
    'W4': "Ulendo Airlink",
    'W5': "馬漢航空",
    'W6': "維茲航空",
    'W7': "黎巴嫩之翼",
    'W8': "加拿大噴氣機航空",
    'W9': "英國維茲航空",
    'WA': "荷蘭皇家城市短途航空",
    'WB': "盧安達航空",
    'WC': "宏都拉斯哥倫比亞航空",
    'WD': "Modern Logistics",
    'WE': "微笑泰航",
    'WF': "維德勒航空",
    'WG': "陽翼航空",
    'WH': "西德空中廣告航空",
    'WI': "懷特航空",
    'WJ': "JetSmart Argentina",
    'WK': "雪絨花航空",
    'WL': "World Atlantic Airlines",
    'WM': "向風群島航空",
    'WN': "西南航空",
    'WO': "Swoop ",
    'WP': "安特衛普航空",
    'WR': "西捷安可航空",
    'WS': "西捷航空",
    'WT': "Swiftair",
    'WU': "烏克蘭維茲航空",
    'WV': "Westair Aviation",
    'WW': "M Jets International Sdn Bhd",
    'WW': "WOW航空",
    'WX': "城捷航空",
    'WY': "阿曼航空",
    'WZ': "紅翼航空",
    'X0': "新疆航空",
    'X1': "Hahn Air Technologies GmbH",
    'X2': "新華航空",
    'X3': "TUI fly Deutschland",
    'X4': "Air Excursion",
    'X5': "歐羅巴快運航空",
    'X7': "ACE Belgium Freighters",
    'X8': "Airmax S.A.",
    'X9': "艾維恩快運",
    'XA': "美國航空無線電公司",
    'XB': "國際航空運輸協會",
    'XC': "克雷頓航空",
    'XD': "Airlines Reporting Corporation",
    'XE': "JSX ",
    'XF': "Mongolian Airways Cargo",
    'XG': "德國極光快線",
    'XJ': "泰國亞洲航空X",
    'XK': "科西嘉航空",
    'XL': "厄瓜多南美航空",
    'XM': "Zimex Aviation",
    'XN': "快速航空",
    'XO': "XplorAsia Airways",
    'XP': "Xtra Airways",
    'XQ': "極光快線",
    'XR': "Corendon Airlines Europe",
    'XS': "國際航空電訊集團公司",
    'XT': "印尼全亞洲航空公司",
    'XU': "非洲快運航空",
    'XW': "酷鳥航空",
    'XY': "納斯航空",
    'XZ': "南非航空快運",
    'Y1': "旅遊技術聯繫",
    'Y2': "Air Century",
    'Y3': "獅鷲航空",
    'Y4': "沃拉里斯航空",
    'Y5': "Golden Myanmar Airlines",
    'Y6': "AB Aviation",
    'Y7': "北星航空",
    'Y8': "金鵬航空",
    'Y9': "基什航空",
    'YB': "加拿大港灣航空",
    'YC': "亞馬爾航空",
    'YD': "Synergy Aviation",
    'YE': "Yanair",
    'YF': "Department of National Defence ",
    'YG': "圓通航空",
    'YH': "Sunsplash Aviation",
    'YK': "交通航空",
    'YL': "利比亞之翼",
    'YM': "蒙特內哥羅航空",
    'YN': "魁北克航空",
    'YO': "摩納哥直升機航空",
    'YR': "TAR Aerolíneas",
    'YS': "歐洲區域航空",
    'YT': "雪人航空",
    'YU': "歐洲大西洋航空",
    'YV': "美莎航空",
    'YW': "諾斯特姆航空",
    'YX': "共和航空",
    'YZ': "Sonoco ThermoSafe",
    'Z2': "菲律賓亞洲航空",
    'Z3': "Bidzy Ta Hot AANA Corporation",
    'Z4': "扎格羅斯噴射航空",
    'Z7': "Amaszonas Uruguay",
    'Z8': "Línea Aérea Amaszonas",
    'ZA': "天空吳哥航空",
    'ZB': "阿爾巴尼亞航空",
    'ZC': "峽谷航空",
    'ZD': "Ewa Air",
    'ZE': "易斯達航空",
    'ZF': "藍色航空",
    'ZG': "ZIPAIR Tokyo",
    'ZH': "深圳航空",
    'ZI': "藍鷹航空",
    'ZJ': "Air Routing International",
    'ZK': "Aircompany ZetAvia",
    'ZL': "區域快線",
    'ZM': "瑪納斯航空",
    'ZN': "Navegacion y Servicios Aéreos Canarios",
    'ZO': "七彩雲南通用航空",
    'ZP': "Paranair",
    'ZR': "Aviacon Zitotrans",
    'ZS': "Azzurra Air",
    'ZT': "泰坦航空",
    'ZU': "Ethiopian Mozambique Airlines",
    'ZV': "扎格羅斯山航空",
    'ZW': "威斯康辛航空公司",
    'ZX': "喬治亞航空",
    'ZY': "中航貨運航空有限公司",
};

module.exports = function(iata) {
    return dict[iata.toUpperCase()];
};
